### ISSUE TITLE
Training code for ok

### ISSUE THREAD

**Issue by kebijuelun** [salesforce/LAVIS#125]
![image](https://user-images.githubusercontent.com/29164878/218048329-1b224504-ef83-4f41-921b-778b44d97ff0.png)

**Comment by kebijuelun** [comment]
> The current codebase supports training on these datasets.

Hi, If found that current BLIP2 codebase need some modification for VQAv2 and OKVQA fine-tune. 
The modification I did:
- `samples["text_output"]` -> `samples["answer"]`
- `self.max_text_length` -> `self.max_txt_len`
- Repeat inputs based on the samples["n_answers"] (like BLIP1)
the modified forward function in https://github.com/salesforce/LAVIS/blob/main/lavis/models/blip2_models/blip2_t5.py#L99 as follows
```python
    def forward(self, samples):
        image = samples["image"]
        image_embeds = self.ln_vision(self.visual_encoder(image))
        image_atts = torch.ones(image_embeds.size()[:-1], dtype=torch.long).to(
            image.device
        )

        query_tokens = self.query_tokens.expand(image_embeds.shape[0], -1, -1)
        query_output = self.Qformer.bert(
            query_embeds=query_tokens,
            encoder_hidden_states=image_embeds,
            encoder_attention_mask=image_atts,
            return_dict=True,
        )

        inputs_t5 = self.t5_proj(query_output.last_hidden_state)
        atts_t5 = torch.ones(inputs_t5.size()[:-1], dtype=torch.long).to(image.device)

        with torch.cuda.amp.autocast(dtype=torch.float32):
            input_tokens = self.t5_tokenizer(
                samples["text_input"],
                padding="longest",
                truncation=True,
                max_length=self.max_txt_len,
                return_tensors="pt",
            ).to(image.device)
            output_tokens = self.t5_tokenizer(
                samples["answer"],
                padding="longest",
                truncation=True,
                max_length=self.max_txt_len,
                return_tensors="pt",
            ).to(image.device)

            batch_input_tokens_input_ids = []
            batch_input_tokens_atts = []
            batch_atts_t5 = []
            batch_inputs_t5 = []

            for b, n in enumerate(samples["n_answers"]):
                batch_input_tokens_input_ids += [input_tokens.input_ids[b]] * n
                batch_input_tokens_atts += [input_tokens.attention_mask[b]] * n
                batch_atts_t5 += [atts_t5[b]] * n
                batch_inputs_t5 += [inputs_t5[b]] * n
            batch_input_tokens_input_ids = torch.stack(batch_input_tokens_input_ids, dim=0)
            batch_input_tokens_atts = torch.stack(batch_input_tokens_atts, dim=0)
            batch_atts_t5 = torch.stack(batch_atts_t5, dim=0)
            batch_inputs_t5 = torch.stack(batch_inputs_t5, dim=0)

            encoder_atts = torch.cat([batch_atts_t5, batch_input_tokens_atts], dim=1)

            targets = output_tokens.input_ids.masked_fill(
                output_tokens.input_ids == self.t5_tokenizer.pad_token_id, -100
            )

            inputs_embeds = self.t5_model.encoder.embed_tokens(batch_input_tokens_input_ids)
            inputs_embeds = torch.cat([batch_inputs_t5, inputs_embeds], dim=1)

            outputs = self.t5_model(
                inputs_embeds=inputs_embeds,
                attention_mask=encoder_atts,
                decoder_attention_mask=output_tokens.attention_mask,
                return_dict=True,
                labels=targets,
            )
            loss = outputs.loss

            return {"loss": loss}
```
- The blip2 okvqa finetuning config file:
```
model:
  arch: blip2_t5
  model_type: pretrain_flant5xl
  load_finetuned: False
  use_grad_checkpoint: True
  # freeze_vit: False
  freeze_vit: True

datasets:
  ok_vqa: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
          # image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
          # image_size: 224
    text_processor:
        train:
          name: "blip_question"
        eval:
          name: "blip_question"

run:
  task: vqa
  # optimization-specific
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  weight_decay: 0.02
  max_epoch: 7
  # batch_size_train: 16
  batch_size_train: 1
  batch_size_eval: 8
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  # num_beams: 256
  num_beams: 5
  num_ans_candidates: 128
  # num_ans_candidates: 96
  inference_method: "rank"

  seed: 42
  output_dir: "output/BLIP2/OKVQA"

  amp: False
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
```

- In addition to the above modifications, I also modified some configurations for training on V100 GPU
  - bfloat16 -> float32 
  - batch_size_train: 16->1
  - num_beams: 256 -> 5
  - freeze_vit: False -> freeze_vit: True

After the afore mentioned changes, the fine-tune accuracy on OK-VQA is **47.49**.
![image](https://user-images.githubusercontent.com/29164878/218689069-bbba21d9-318c-4de7-a697-23aa9eeaafa1.png)

I have several questions that I hope someone can help me:
  - What is the precision of finetune of the original BLIP2 on okvqa? (I don't see any result in the paper.)
  - If the accuracy is significantly higher than my reproduce accuracy (**47.49**), What is the possible reasons for the accuracy reduction?
