### ISSUE TITLE
load_model without internet connection

### ISSUE THREAD

**Issue by gunesevitan** [salesforce/LAVIS#176]
I want to use some of the models in a Kaggle code competition, so I'll upload them to Kaggle and load from a path in an offline environment.

I'm not sure `load_model` or `load_model_and_preprocess` are compatible with paths. I tried passing path of a pretrained model as `checkpoint` argument for `load_model`, it still tried to download it. I couldn't find a workaround for this issue? How should I proceed?

**Comment by dxli94** [comment]
I can't think of an easy solution for this purpose.

There are model weights that have to be downloaded before the model instance can be instantiated and returned.

I am not sure this can be achieved without changing the model definition.

**Comment by gunesevitan** [comment]
I think simplest way to do it is downloading default config and overriding `PRETRAINED_MODEL_CONFIG_DICT` of the model class. I'm not sure it worked or not but it didn't try to download on local. I haven't tried this workaround on another environment yet.

```
from lavis.models import BlipCaption, load_model_and_preprocess

BlipCaption.PRETRAINED_MODEL_CONFIG_DICT['base_coco'] = 'path/to/blip_caption_base_coco.yaml'
model, _, _ = load_model_and_preprocess(name='blip_caption', model_type='base_coco')
```

**Comment by junhocho** [comment]
Actually, this is quite necessary. Even though I use `.cach/huggingface/` , it seems still asking internet connection in isolated server.

**Comment by gunesevitan** [comment]
I'm glad that lavis inherently allows this with very few modifications. I tried this workaround on BLIP model and it didn't ask for internet connection in my local machine.

`blip_caption_base_coco.yaml`, `blip_coco_caption_base.pth` and `med_config.json` have to be downloaded.

Change urls to paths in `blip_caption_base_coco.yaml`.
```
model:
  arch: blip_caption
  load_finetuned: True

  pretrained: absolute/path/to/model_base_capfilt_large.pth
  finetuned: absolute/path/to/blip_coco_caption_base.pth

  # vit encoder
  vit_type: "base"
  vit_grad_ckpt: False
  vit_ckpt_layer: 0

  image_size: 384

  # bert config
  med_config_path: absolute/path/to/med_config.json

  # generation configs
  prompt: "a picture of "
```

Use this function to load model and preprocessors.

```
def load_offline(model_name, model_type, model_config_path):

    model_class = registry.get_model_class(model_name)
    model_class.PRETRAINED_MODEL_CONFIG_DICT[model_type] = model_config_path
    model, image_processor, text_processor = load_model_and_preprocess(name=model_name, model_type=model_type)

    return model, image_processor, text_processor
```
