### ISSUE TITLE
How to replicate BLIP-2 results with a dataset that is already dowloaded?

### ISSUE THREAD

**Issue by dshatwell23** [salesforce/LAVIS#655]
Hello,

I want to replicate the results of BLIP-2 on image-to-text retrieval. I understand that I need to run the `eval_ret_coco.sh` script, which uses `ret_coco_eval.yaml` config file to set up the experiments.

I've previously downloaded COCO, and I'd like to inlcude the path to the dataset in the config file, but I don't know how to include it.

Should I replace the commented line that says "storage" in `ret_coco_eval.yaml` with the path to my dataset?

```
datasets:
  coco_retrieval: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 364
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
#     build_info:
#         images:
#             storage: '/export/share/datasets/vision/coco/images/'
```

Thank you.
