### ISSUE TITLE
Abnormal in warmup learning rate

### ISSUE THREAD

**Issue by Richar-Du** [salesforce/LAVIS#72]
When I use the warmup learning rate, the learning rate curve is abnormal. It jumps to the highest learning rate after finishing the first epoch.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/55051961/209520804-07372981-a7ad-4d60-aabb-ebcdcc1fd204.png">

My configuration in the `caption_coco_large_ft.yaml` is as follows:

```
run:
  task: aokvqa_captioning # captioning
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 0
  warmup_steps: 6000
  init_lr: 2e-6
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 10
  batch_size_train: 4
  batch_size_eval: 8
  num_workers: 4
```

Maybe there is something wrong with the scheduler, could you check the code? Thanks in advance.
